CREATE TABLE reservations (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255) DEFAULT '',
  last_name VARCHAR(255) DEFAULT '',
  email VARCHAR(255),
  phone VARCHAR(255) DEFAULT '',
  start_date DATE,
  end_date DATE,
  room_id INTEGER,
  processed INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
